
# Code Highlight theme
# Available value:
#    normal | night | night yilia | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
# night yilia - https://github.com/litten/hexo-theme-yilia
highlight_theme: normal
#header decoration
slideshow: false 
ribban_bg: false
particle_bg: true 

#CDN settings;
bootstrapJS_CDN: https://cdn.staticfile.org/twitter-bootstrap/3.4.1/js/bootstrap.min.js
bootstrapCSS_CDN: https://cdn.staticfile.org/twitter-bootstrap/3.4.1/css/bootstrap.min.css
jquery_CDN: https://cdn.staticfile.org/jquery/2.2.4/jquery.min.js

# Sidebar settings
sidebar: true                       # whether or not using Sidebar.
sidebar-about-description: "INNOVATION IS KING!"
sidebar-avatar: /img/avatar/logo.png      # use absolute URL, seeing it's used in both `/` and `/about/`
widgets:
- featured-tags
- short-about
- recent-posts
- archive
- friends-blog
#- category
# widget behavior
## Archive
archives-img: /img/header_img/archives-widget.jpg
archive_type: 'monthly'
show_count: true
## Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 0              # A tag will be featured if the size of it is more than this condition value

## Friends
friends: [
    {
        title: "ACE theme",
        href: "http://www.sumoon.com"
    }
#    ,
#    {
#        title: "your blog",
#        href: "http://"
#    }
]
## Nav Menus
navmenu: [
{
   title: "menu1",
   url: "#",        
},
{
   title: "menu2",
   url: "#",        
},
{
   title: "menu3",
   url: "#",        
},
{
   title: "menu3",
   url: "#",        
},
{
   title: "menu5",
   url: "#",        
}
]
#sticky post tag
sticky_tag: "Sticky"

# Analytics settings
#Baidu Analytics
ba_track_id: 
# Google Analytics
ga_track_id:           # Format: UA-xxxxxx-xx
ga_domain: 


# SNS settings
# SNS Share
# Reference: https://github.com/overtrue/share.js
share: true
# RSS: false
# weibo_username:     Demonbaneen
# zhihu_username:     Demonbane
github_username:    kinggozhang
# twitter_username:   Demonbane_x
# facebook_username:  xxx
# linkedin_username:  xxx
# Build settings
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`


# Disqus settings
#disqus_username: your-disqus-ID

# Valine settings 
# Valine depends on leancloud, please signup leancloud to get appid/appkey. https://valine.js.org/quickstart.html
enable_valine: false
leancloud_appid: ''
leancloud_appkey: ''
enable_leancounter: true
